######################################################################
##
## Filename: uart_byte_rx_tb.udo
## Created on: Fri Oct 15 15:06:08 中国标准时间 2021
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
