######################################################################
##
## Filename: xulie_signal_tb.udo
## Created on: Thu Aug 19 22:12:49 中国标准时间 2021
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
