######################################################################
##
## Filename: cnt_led_tb.udo
## Created on: Wed Aug 18 16:43:38 中国标准时间 2021
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
