######################################################################
##
## Filename: ram.udo
## Created on: Mon Oct 25 9:57:25 中国标准时间 2021
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
