######################################################################
##
## Filename: pll_test_tb.udo
## Created on: Wed Aug 04 0:49:36 中国标准时间 2021
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
