######################################################################
##
## Filename: uart_byte_tx_tb.udo
## Created on: Tue Aug 10 17:56:56 中国标准时间 2021
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
