######################################################################
##
## Filename: uart_tx_tb.udo
## Created on: Thu Sep 02 18:10:09 中国标准时间 2021
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
