######################################################################
##
## Filename: uart_string_tb.udo
## Created on: Thu Sep 02 20:14:29 中国标准时间 2021
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
