######################################################################
##
## Filename: uart_tx_tb.udo
## Created on: Thu Oct 14 20:59:20 中国标准时间 2021
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
